version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: vue-client
    volumes:
      - /var/www/linkshortener.yanramos.com.br:/app/linkshortener.yanramos.com.br
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: spring-api
    ports:
      - "2100:2100"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
