services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ls
      - MYSQL_DATABASE=ls
      - MYSQL_USER=ls
      - MYSQL_PASSWORD=ls
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
